### ISSUE TITLE
Getting `deployment_perms_error` when trying to run this action since June 16

### ISSUE THREAD

**Issue by idanarye** [actions/deploy-pages#188] opened 2023-06-18 18:04 UTC
Two days ago (June 16) this action stopped working. This is the first run where I've seen it fail - https://github.com/idanarye/bevy-yoleck/actions/runs/5293695779/jobs/9592352399.

When I look at the logs, I see these lines repeating 5 times after the `Created deployment for <...>, ID: <...>` log:
```
Getting Pages deployment status...
Current status: deployment_in_progress
```

And then these lines repeating over a hundred times:
```
Getting Pages deployment status...
Current status: deployment_perms_error
```

Followed by:
```
Error: Timeout reached, aborting!
Error: Timeout reached, aborting!
Canceling Pages deployment...
Canceled deployment with ID <...>
```

Note that:
* I've upgraded from v1 to `actions/deploy-pages@v2`, but the problem still repeats.
* When I tried to rerun older runs that did pass, this action failed.

So I think maybe something was changed in GitHub that either broke this action or caused it to require some additional configuration/permissions.

Note that six hours before that first failed run linked above I had a run that managed to pass and deploy the pages: https://github.com/idanarye/bevy-yoleck/actions/runs/5285227962/jobs/9563650017. So whatever changed probably happened during these six hours.

**Comment by onbjerg** [comment] 2023-06-19 08:48
We get this too, opened up a PR to bump to v2 but sad that this seems like it would not fix it. Did you by chance find a workaround?

**Comment by idanarye** [comment] 2023-06-19 11:16
@onbjerg I could not. The error is about permissions, so I tried adding more permissions that maybe could have been related (specifically I tried `deployments: write` and `actions: write`. They probably don't matter, but I was just trying things out) but it didn't work.

**Comment by onbjerg** [comment] 2023-06-19 11:20
Hitting the endpoint manually using `gh` seems to yield a response of e.g.

```json
{
  status: ""
}
```

which is a bit odd. The deployments do show up under the "Environments" tab of the repository as well, all marked as failed, even though you can explore the deployments and they seem to look fine 🤷🏻‍♂️

**Comment by ViliamVadocz** [comment] 2023-06-19 15:57
I am encountering the same issue: [failing job](https://github.com/ViliamVadocz/nvidia-video-codec-sdk/actions/runs/5311954120/jobs/9618340359).
My [workflow file](https://github.com/ViliamVadocz/nvidia-video-codec-sdk/actions/runs/5311954120/workflow) is a bit simpler that @idanarye's. Maybe this will help with reproducibility.

**Comment by xxchan** [comment] 2023-06-19 18:11
Same here. Begin to fail from 2 days ago
https://github.com/risingwavelabs/risingwave/actions/workflows/doc.yml

<img width="1157" alt="image" src="https://github.com/actions/deploy-pages/assets/37948597/86c9cbf9-deeb-4489-9ae4-c05bf8b6d9f4">

also

              I am hitting this error in my recent rustdoc deployments: https://github.com/DCNick3/shin/actions/runs/5300334374/jobs/9593874612

Is there anywhere I can find details about the "incorrect file permissions"?

_Originally posted by @DCNick3 in https://github.com/actions/deploy-pages/issues/187#issuecomment-1595882786_

**Comment by xxchan** [comment] 2023-06-19 18:15
cc @tsusdere

**Comment by YiMysty** [comment] 2023-06-19 18:45
👋 there is a README updated today.
https://github.com/actions/upload-pages-artifact#file-permissions

You can use the similar command to troubleshooting the incorrect file permissions :)

**Comment by yoannchaudet** [comment] 2023-06-19 18:46
Apologies for not getting the documentation published on time.

If you get a permissions issue, that means your artifacts are not in the form we expect. You can fix that with an extra step, see https://github.com/actions/upload-pages-artifact#file-permissions.

We used to proactively fix permissions on your behalf but for many sites (with lots of files), that would delay Pages deployments by a lot and not be needed. We decided to just surface the error slightly better and document a mitigation step. Also note that this typically only happens if you have a custom workflow (dockers builds can be impacted).

**Comment by onbjerg** [comment] 2023-06-19 19:21
Just a note here from me, turns out that the only file with incorrect permissions for my Rust based project was the `.lock` file that Cargo had snuck in to my rustdoc build 😄

**Comment by idanarye** [comment] 2023-06-19 19:33
That did the trick.

**Comment by antonengelhardt** [comment] 2023-07-02 21:54
Thanks everyone. It worked.

Additionally, i added the following for my Rust project:

```
echo "<meta http-equiv=\"refresh\" content=\"0; url=build_wheel\">" > target/doc/index.html
```

Maybe the [final workflow file](https://github.com/antonengelhardt/wasm-oidc-plugin/blob/main/.github/workflows/documentation.yml) is more informative

**Comment by JamesMGreene** [comment] 2023-07-10 16:01
@onbjerg 

> Hopefully that was just it, although I feel like this should have been a breaking version bump on @actions/upload-pages-artifact? 😄

I agree. I'm going to revert that change in the `v1` line for `upload-pages-artifact` and cut a new `v2.0.0` / `v2` release for the `chmod` removal. Sorry about that! 😅 

I'll drop an update here once that's cleaned up.

**Comment by onbjerg** [comment] 2023-07-10 16:30
Appreciate it!

**Comment by JamesMGreene** [comment] 2023-07-10 18:36
The part that most concerns me now is that it sounds like the `deployment_perms_error` status wasn't treated as a terminating/final status, which it should've been. 🤔

> And then these lines repeating over a hundred times:
> 
> ```
> Getting Pages deployment status...
> Current status: deployment_perms_error
> ```
> 
> Followed by:
> 
> ```
> Error: Timeout reached, aborting!
> Error: Timeout reached, aborting!
> Canceling Pages deployment...
> Canceled deployment with ID <...>
> ```

We should still investigate and/or write a test for that scenario. 🧪

**Comment by JamesMGreene** [comment] 2023-07-10 18:55
Ah, the repetitive error status until timing out was unfortunately a clerical error on our part: we forgot to publish the latest release containing the changes from PR #187.

If you update to use [`v2.0.3`](https://github.com/actions/deploy-pages/releases/tag/v2.0.3) or the latest `v2` major tag, the repetitive status polling should now be gone in the case of an file permissions error.

Such errors will need to be corrected before attempting to deploy, by doing something similar to one of the following:
- correcting your file permissions ahead of time so that they are already correct in `git` when checking them out from the repository
- using the `actions/upload-pages-artifact@v1` tag, specifically (`@v2` removed the formerly built-in `chmod` fix as it causes unnecessary slowdowns if your file permissions are already correct)
- adding another step into your Actions workflow before uploading the Pages artifact to fix any invalid permissions, e.g. the [example fixes included in the README of `actions/upload-pages-artifact@v2`](https://github.com/actions/upload-pages-artifact#file-permissions)

**Closed** 2023-07-10 18:56 UTC
