### ISSUE TITLE
The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource

### ISSUE THREAD

**Issue by noraj** [actions/deploy-pages#236] opened 2023-10-07 18:32 UTC
My workflow: https://github.com/IDLFAC/CyberMots/blob/d44c761d6c81c72ce60e32f1d4b43b25d9c15ff4/.github/workflows/ruby.yml

- build job ✅ 
- deploy job ❌ 

deploy job logs https://github.com/IDLFAC/CyberMots/actions/runs/6442789709/job/17493982576

The error itself is not helpful:

```
Error: Creating Pages deployment failed
Error: HttpError: invalid json response body at https://api.github.com/repos/IDLFAC/CyberMots/pages/deployments reason: Unexpected end of JSON input
```

If I check the Artifact exchange URL:

```json
{
  "$id": "1",
  "innerException": null,
  "message": "The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.",
  "typeName": "Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server",
  "typeKey": "UnauthorizedRequestException",
  "errorCode": 0,
  "eventId": 3000
}
```

I know the `permissions` is set globally and not on the deploy job directly but this is working on others workflows on other projects.

When I check the API message:

```json
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}
```

But the repository does exists and is configured to use Github Pages with Github Actions (settings at https://github.com/IDLFAC/CyberMots/settings/pages).

Whatever the issue is, I think the error messages and error handling could be greatly improved.

**Comment by nilsamd** [comment] 2023-10-11 20:52
I have a similar issue when running against gitenterprise 3.8. In the same context, I also observed the server returning status 500.

**Comment by noraj** [comment] 2023-10-23 17:13
Similar issues:

- https://github.com/actions/upload-artifact/issues/319
- https://stackoverflow.com/questions/70568350/github-build-and-deploy-error-no-uploaded-artifact-was-found
-

**Comment by galenseilis** [comment] 2023-10-28 19:29
I appear to be having [a similar issue](https://github.com/galenseilis/Mjolnir/issues/1) except that when I tried to remove a non-ASCII character it did not resolve the issue.

**Comment by JamesMGreene** [comment] 2023-11-20 17:42
I'm going to close this as a duplicate of #185 but your mention of the Artifacts service error may prove to be useful.
We've filed an internal bug to investigate this one further as well. Thank you! 🙇

**Closed by JamesMGreene** 2023-11-20 17:42 UTC
Labels: duplicate
