### ISSUE TITLE
Workflow cancellation left pages deploy wedged

### ISSUE THREAD

**Issue by sfreilich** [actions/deploy-pages#22] opened 2022-03-17 13:18 UTC
I recently had a problem where my pages deploy was stuck in a state where it would perpetually fail with:

```
Deployment request failed for 75152aed304ba9378fd527c226e9849ca39d5eda due to in progress deployment. Please cancel 4cb1cd27f0f1bceb7df2e4b7cb82785922dc978d first or wait for it to complete.
```

(Created a thread about that here: https://github.community/t/pages-deploy-wedged-incorrect-request-failed-due-to-in-progress-deployment/234793)

I eventually got the issue unwedged manually using the GitHub API to delete the relevant deployments. It seems what happened was a deploy job was cancelled midway through, but that cancellation failed:  https://github.com/google/ink-stroke-modeler/runs/5457992551

```
Error: Error: Request failed with status code 404
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Sending telemetry for run id 1948901688
Deployment cancellation failed Error: Request failed with status code 401
[...]
url: 'https://api.github.com/repos/google/ink-stroke-modeler/pages/deployment/cancel/4cb1cd27f0f1bceb7df2e4b7cb82785922dc978d',
[...]
```

That URL seems to be coming from here:  https://github.com/actions/deploy-pages/blob/b4051408bb8ab14e734a766b8291a39c4df701c1/src/index.js#L20

But I'm confused because I don't see that API endpoint in the documentation: https://docs.github.com/en/rest/reference/pages

And I wasn't able to get it to work myself with curl, I had to use the deployments endpoint to search for and delete the relevant deployments instead: https://docs.github.com/en/rest/reference/deployments#delete-a-deployment

Was this problem due to a bug in `cancelHandler`?

**Comment by DmitryGrayscale** [comment] 2022-03-17 13:21
got the same today, but with error 400 (same description though: Deployment request failed due to in progress deployment)

**Comment by hsm** [comment] 2022-03-17 13:23
Same issue here. I’ve created a minimal example here: https://github.com/hsm/pages/

Succeeds initially and then fails every time afterwards.

Steps to reproduce:

1. Create a public repository with an index.html of your choice.
2. Create a branch with the name `gh-pages`. This will automatically trigger deployment to Github Pages successfully.
3. Make a change in the index.html file on the `gh-pages` branch. This time the automatic deployments fails for me with an error message like this one:

**Comment by leemlb06pmi** [comment] 2022-03-17 13:46
I'm getting this same problem today - potentially a process change we don't know about? Do we have any solutions as of yet?

**Comment by manuelmeurer** [comment] 2022-03-17 13:51
Same problem here:
https://github.com/manuelmeurer/manuelmeurer.github.io/runs/5586680873

**Comment by thomiz** [comment] 2022-03-17 13:51
Same issue in my [public repo](https://github.com/HL7Norway/VkpObservation/runs/5586709851?check_suite_focus=true)

**Comment by hassaanbinaslam** [comment] 2022-03-17 13:52
Same issue here
https://github.com/hassaanbinaslam/myblog/runs/5586630206?check_suite_focus=true

**Comment by HavenTong** [comment] 2022-03-17 13:57
Same issue here
https://github.com/HavenTong/HavenTong.github.io/runs/5586948035?check_suite_focus=true

**Comment by Ryo-N7** [comment] 2022-03-17 13:59
same issue here: 

https://github.com/Ryo-N7/Ryo-N7.github.io/runs/5587011624?check_suite_focus=true

**Comment by cnftstats** [comment] 2022-03-17 14:00
Same issue here:
[](https://github.com/cnftstats/borgs/runs/5586908884?check_suite_focus=true)

**Comment by eliasnemr** [comment] 2022-03-17 14:01
same issue

**Comment by DavidMorenoDev** [comment] 2022-03-17 14:26
same issue but error 400

**Comment by AmaniZandalari** [comment] 2022-03-17 14:27
same issue, error 400

**Comment by FabianBartl** [comment] 2022-03-17 15:37
same issue, but error 500

**Comment by kera-cudmore** [comment] 2022-03-17 15:50
I'm currently having the same issue too, error 400

**Comment by rocketstack-matt** [comment] 2022-03-17 16:06
I had this issue for the last couple of hours, but seems to have been related to this outage - https://www.githubstatus.com/incidents/sksd097hm0y5 . . . a blank change to force a redeploy of the gh-pages branch has worked having failed multiple attempts in the prior couple of hours.

**Comment by hsm** [comment] 2022-03-17 16:21
It seems to be working now for my toy example.

**Comment by leemlb06pmi** [comment] 2022-03-17 16:34
I got one deploy out the door - but the subsequent change failed with the same 400 error

**Comment by leo2105** [comment] 2022-03-17 16:38
Same error here...
https://github.com/leo2105/mywebsite/actions/runs/1999598076

**Comment by kera-cudmore** [comment] 2022-03-17 16:40
> I got one deploy out the door - but the subsequent change failed with the same 400 error

Same here 😬

**Comment by mrbuche** [comment] 2022-03-17 16:48
I think GitHub is having some issues today, and it's probably nothing we are ALL doing wrong...

**Comment by abubelinha** [comment] 2022-03-17 16:56
Me too!
Thanks @sfreilich for opening [this](https://github.community/t/pages-deploy-wedged-incorrect-request-failed-due-to-in-progress-deployment/234793/3) and linking back here.
@abubelinha

**Comment by counter-prop** [comment] 2022-03-17 16:57
Same issue

**Comment by awagmi** [comment] 2022-03-17 17:04
same here. i guess we just have to wait

**Comment by Clarit7** [comment] 2022-03-17 17:06
Same issue. Like @mrbuche said, it should be GitHub problem.

**Comment by YiMysty** [comment] 2022-03-17 17:06
👋 we have identified the potential issue due to a recent deployment. We gonna deploy a fix soon. Currently pages deployment is 1 hour per repo per pages deployment. Will notified again when the fix released. Deeply sorry for the incident.

**Comment by jsntn** [comment] 2022-03-17 17:13
same issue, error 400

**Comment by YiMysty** [comment] 2022-03-17 17:14
Fix has been rolled out. For current locked deployment it may take up to 1 hour to fully mitigate. Sorry for causing the issue.

**Comment by h3x311** [comment] 2022-03-17 17:15
same here.

**Comment by modanesh** [comment] 2022-03-17 17:16
Same

**Comment by abubelinha** [comment] 2022-03-17 17:20
Saw a similar [incident report](https://www.githubstatus.com/incidents/sksd097hm0y5) in githubstatus.com

There it saids "resolved" one hour ago but my github pages deployment is still failing.
@YiMysty is this a different issue?

**Comment by YiMysty** [comment] 2022-03-17 17:25
> Saw a similar [incident report](https://www.githubstatus.com/incidents/sksd097hm0y5) in githubstatus.com
> 
> There it saids "resolved" one hour ago but my github pages deployment is still failing. @YiMysty is this a different issue?

If you are seeing the same error described below
```
Deployment request failed for ... due to in progress deployment. Please cancel ... first or wait for it to complete.
```
it's due to another issue. The mitigation may take up to 1 hour since the patch I mentioned above, thank you for your patient.

**Comment by Onique-Unique** [comment] 2022-03-17 17:26
is the issue resolved yet?, as i'm experiencing the same currently.

**Comment by DarkTornado** [comment] 2022-03-17 17:26
I have the a same issue for 4 hours. It rarely works, but usually fails.

**Comment by sfreilich** [comment] 2022-03-17 17:28
I think I'm in the unlucky position here of writing up an issue from a while ago (on March 7) in the middle of an unrelated (?) outage that affects the same thing.

**Comment by abubelinha** [comment] 2022-03-17 17:37
> it's due to another issue. The mitigation may take up to 1 hour since the patch I mentioned above, thank you for your patient.

Thanks @YiMysty 
I was asking because I don't understand why, if github knows there is an issue which _will **still** last for one hour_ (hopefully) ... why is the [githubstatus](https://githubstatus.com) page _**already**_ showing all green flags?   That's not fair.

**Comment by RagingTiger** [comment] 2022-03-17 17:39
Mine is now working properly (after rerun): https://github.com/RagingTiger/tensorflowjs-mobilenet-transfer-learning/actions/workflows/pages/pages-build-deployment

**Comment by solidwaterslayer** [comment] 2022-03-17 17:39
mee 2

**Comment by Onique-Unique** [comment] 2022-03-17 17:48
> Mine is now working properly (after rerun): https://github.com/RagingTiger/tensorflowjs-mobilenet-transfer-learning/actions/workflows/pages/pages-build-deployment

did you have to rerun all jobs?

**Comment by Onique-Unique** [comment] 2022-03-17 17:52
> > > Mine is now working properly (after rerun): https://github.com/RagingTiger/tensorflowjs-mobilenet-transfer-learning/actions/workflows/pages/pages-build-deployment
> > 
> > 
> > did you have to rerun all jobs?
> 
> Wait mines is working now too. I didn't have to rerun. It reran itself.

mines still not working. how sad

**Comment by Onique-Unique** [comment] 2022-03-17 18:04
> > > > Mine is now working properly (after rerun): https://github.com/RagingTiger/tensorflowjs-mobilenet-transfer-learning/actions/workflows/pages/pages-build-deployment
> > > 
> > > 
> > > did you have to rerun all jobs?
> > 
> > 
> > Wait mines is working now too. I didn't have to rerun. It reran itself.
> 
> mines still not working. how sad

update. it automatically reruns and deploy successfully

**Comment by RagingTiger** [comment] 2022-03-17 18:05
@Onique-Unique I simply _reran_ the **deploy job** (since that was the one that failed).

**Comment by RagingTiger** [comment] 2022-03-17 18:08
Seems like it's starting to work ... 🎉

**Comment by yoannchaudet** [comment] 2022-03-17 19:03
Hello all, 

I posted an update in https://github.community/t/github-actions-failed-to-deploy-my-site-to-github-pages/239017/4?u=yoannchaudet.

We should all be mitigated by now. Sorry for that. If you do experience any issue again, please re-open the issue!

**Closed by yoannchaudet** 2022-03-17 19:03 UTC

**Comment by harrydehix** [comment] 2022-03-28 14:53
I'm having this problem again.

```
Failed to create deployment for f0d2ba28bf215d8d76054e06ea634ffcd702de65.
{"message":"Deployment request failed for f0d2ba28bf215d8d76054e06ea634ffcd702de65 due to in progress deployment. Please cancel 04032ecc8ca9188587058f0f81246070d9979123 first or wait for it to complete.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}
Error: Error: Request failed with status code 400
Error: Error: Request failed with status code 400
Sending telemetry for run id 2053036488
```

**Comment by mielvds** [comment] 2022-03-28 14:54
same here

**Comment by DarkTornado** [comment] 2022-03-28 15:01
Same issue occurred again.

**Comment by FransBouma** [comment] 2022-03-28 15:04
Same here.

**Comment by harrydehix** [comment] 2022-03-28 15:15
On my repo it doesn't throw an error anymore, but it gets stuck in the "updating_pages" state forever.

**Comment by gilesdring** [comment] 2022-03-28 15:16
Same problem here

**Comment by DanForder** [comment] 2022-03-28 15:37
just had this issue occur 30 minutes ago out of the blue

**Comment by dschwilk** [comment] 2022-03-28 15:39
Same problem here. Not fixed. Deploy step fails.

**Comment by jdmar3** [comment] 2022-03-28 15:41
I have had this issue occur several times in the last hour. This is the most recent fail: 

```
Failed to create deployment for 2de0f5623073e398826052ea668d5bf121a92fa7.
{"message":"Deployment request failed for 2de0f5623073e398826052ea668d5bf121a92fa7 due to in progress deployment. Please cancel 5643d1c07410a7fdfb3f80033f57cb0aa3835c41 first or wait for it to complete.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}
Error: Error: Request failed with status code 400
Error: Error: Request failed with status code 400
Sending telemetry for run id [20](https://github.com/jdmar3/comp426/runs/5723089742?check_suite_focus=true#step:3:20)53314087
```

https://github.com/jdmar3/comp426/runs/5723089742?check_suite_focus=true

**Comment by DarkTornado** [comment] 2022-03-28 15:46
UTC March/28/2022 12:44 : Worked Well

UTC March/28/2022 14:05 : A lot of `Current status: updating_pages` was printed and finally throwed `Error: Request failed with status code 502.`

UTC March/28/2022 14:29 : Same as at `UTC March/28/2022 14:05`.

UTC March/28/2022 14:57 : Same error message with this issue. (Please cancel `commit hash` first or wait for it to complete.)

30 minutes age ~ Now : A lot of `Current status: updating_pages` is printing.

**Comment by Basicprogrammer10** [comment] 2022-03-28 16:08
Same issue here :/

**Comment by LearningGp** [comment] 2022-03-28 16:23
Same problem here

**Comment by artegoser** [comment] 2022-03-28 16:29
Same problem here

**Comment by artegoser** [comment] 2022-03-28 16:31
```Creating deployment with payload:
{
	"artifact_url": "https://pipelines.actions.githubusercontent.com/jzJ0sQwGqjU6H2nAOH11SWcMtLZaT2U9KXgfUtWOaj2a4nM92J/_apis/pipelines/1/runs/36/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "52888fc949a229e0e3f5f7cb5b73b038bbfa0425",
	"oidc_token": "***"
}
Failed to create deployment for 52888fc949a229e0e3f5f7cb5b73b038bbfa0425.
{"message":"Deployment request failed for 52888fc949a229e0e3f5f7cb5b73b038bbfa0425 due to in progress deployment. Please cancel 1866ed4a[15](https://github.com/OOVC/movc-client/runs/5723838913?check_suite_focus=true#step:3:15)b27306c21545c[17](https://github.com/OOVC/movc-client/runs/5723838913?check_suite_focus=true#step:3:17)f760b86a1bfd389 first or wait for it to complete.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}
Error: Error: Request failed with status code 400```

**Comment by harrydehix** [comment] 2022-03-28 16:33
Fixed for me now,

**Comment by ethanabrooks** [comment] 2022-03-28 16:42
> Fixed for me now,

Just a matter of waiting?

**Comment by Ivens-Zhang** [comment] 2022-03-28 16:49
I just supposed that something wrong I had done to cause it.

**Comment by harrydehix** [comment] 2022-03-28 16:51
> > Fixed for me now,
> 
> Just a matter of waiting?

I just tried rerunning the failed jobs again and again, and suddenly it worked.

**Comment by TaylorLancaster12** [comment] 2022-03-28 16:57
I'm also having this issue today on my [public repo](https://github.com/OpenExchangeProduction/oe_css_themes/deployments). Can't get my deploys to run, and all it is is CSS and HTML.

**Comment by vasveena** [comment] 2022-03-28 17:42
I get the same issue. I deleted the existing deployment. After that, the deployment is stuck in "Current status: updating_pages".

**Comment by Lmmmmmm-bb** [comment] 2022-03-28 17:55
I got same issue in this [repo](https://github.com/Lmmmmmm-bb/Octo-Exam/runs/5724913114?check_suite_focus=true). always `Current status: updating_pages`.

**Comment by fffabiang** [comment] 2022-03-28 17:55
I have same issue. Stuck in  `Current status: updating_pages.`

**Comment by rcanelav** [comment] 2022-03-28 17:57
Same here :(

**Comment by GabrieLempert** [comment] 2022-03-28 18:33
same here

**Comment by AlexandreAlvarez59** [comment] 2022-03-28 18:44
Same here T.T

**Comment by aheze** [comment] 2022-03-28 18:59
Anyone find a workaround? Same thing here

**Comment by Jean-Monsieur** [comment] 2022-03-28 19:41
Same here  :(

**Comment by ZoranPandovski** [comment] 2022-03-28 20:01
Delete your previous failing actions and just re-run the latest. It should work now.

**Comment by ZoranPandovski** [comment] 2022-03-28 20:07
Make sure you delete all your previous failing builds and just re-run the latest. Now, it should work

**Comment by vasveena** [comment] 2022-03-28 20:08
Re-deployed without any changes. Works for me now!

**Comment by TaylorLancaster12** [comment] 2022-03-28 20:31
Working now for me as well; deleted my failed workflows and deployed a new change with no issues.

**Comment by yoannchaudet** [comment] 2022-03-28 21:38
Hello 👋,

Just to confirm, it does correspond to our incident this morning https://www.githubstatus.com/incidents/z95g34pl8rdm.

It took us longer than expected to get everything under control again and we identified a few things we will need to improve shortly so it does not happen again. Sorry for the inconvenience.

**Comment by Ivens-Zhang** [comment] 2022-03-29 01:31
> Hello 👋,
> 
> Just to confirm, it does correspond to our incident this morning https://www.githubstatus.com/incidents/z95g34pl8rdm.
> 
> It took us longer than expected to get everything under control again and we identified a few things we will need to improve shortly so it does not happen again. Sorry for the inconvenience.

[It](https://github.com/Ivens-Zhang/Ivens-Zhang.github.io/actions/runs/2053660009) has already worked, Thanks for your contribution!

**Comment by LearningGp** [comment] 2022-03-29 05:00
I met similar problems yesterday, after making some attempts that didn't work, I chose to put it on hold. When retrying this morning, the deployment was successful. There does seem to be an unfinished deployment task, but there is no way to cancel.

**Comment by orchetect** [comment] 2022-08-23 01:00
This same issue is happening now on one of my repos. GitHub Status shows all green.

**Comment by yoannchaudet** [comment] 2022-08-24 19:59
@orchetect We made changes in the last few days (both on the backend and on the [client side](https://github.com/actions/deploy-pages/pull/56) to limit this scenario from happening. In the worse case a deployment should not block another one for more than 10 minutes (previously 60 minutes), in most cases it should have to come to that.

**Comment by orchetect** [comment] 2022-08-24 20:00
@yoannchaudet It took a few hours but did seem to resolve

**Comment by tex0l** [comment] 2022-12-06 14:42
I'm experiencing the same issue right now on my repo: https://github.com/tex0l/tex0l.github.io/

**Comment by ToonTalk** [comment] 2023-01-20 18:06
I intermittently began experiencing this on 7 December have using the Github Desktop for several years without any problems. I saw a suggestion to replace the Github Pages with None at github.com and then restore it to master. But now the entire github.io site has disappeared https://ecraft2learn.github.io/ai/

Can someone please tell me what to enter in the command line to restore gh-pages to the current state of the master repository?

**Comment by jeremy-daley-kr** [comment] 2023-02-12 22:14
@yoannchaudet I saw you closed this. I'm working on a PR to convert the use of `axios` out to the `@actions/github` package, but don't see an answer to @sfreilich question, as I'm wondering it also...

Where is this endpoint?
```js
const pagesCancelDeployEndpoint = `${this.githubApiUrl}/repos/${this.repositoryNwo}/pages/deployment/cancel/${this.buildVersion}`
```
I don't see it documented anywhere.

**Comment by yoannchaudet** [comment] 2023-02-13 23:01
This API is still marked as internal. This is customary for features while they are in Beta so we can make breaking changes without having to go through a regular depreciation process.

Will make a note for the team to decide if we publish it now or hold a bit longer.

**Comment by Peter-developer01** [comment] 2023-07-03 13:38
Same problem. Any ideas?

**Comment by fmaussion** [comment] 2023-07-03 13:47
@Peter-developer01 I also landed here today which I think hints at server problems at github. For me waiting and re-triggering a build after wait seems to have solved the issue (15 minutes maybe?)
